name: Cypress testing

on:
  push:
    branches:
      - main 

jobs:
  cypress_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npx cypress run

      - name: Set up GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./cypress/reports/html
          publish_branch: gh-pages 

      - name: Update Description with GitHub Pages link
        run: |
          echo "Find the Cypress report here: https://nikdesu.github.io/Cypress-Task-3/reports" > description.txt # Update with your GitHub username and repository name
          git checkout main
          git add description.txt
          git commit -m "Add link to GitHub Pages in description"
          git push origin main

