name: Cypress Tests

on:
  push:
    branches:
      - main # Replace with your branch name

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install 
        
      - name: Run Cypress tests
        run: npx cypress run

      - name: Upload Cypress test results to Dashboard
        run: npx cypress-dashboard upload --key ${{ 53cbd7a7-a44b-4b0b-8cdf-4cd4d51b40ee }} --parallel
